version: '3.7'
services:
  blog:
    image: ghost:3-alpine
    ports:
      - 2368:2368
    environment:
      url: https://blog.example.com
      mail__from: "'Ghost Blog' <blog@example.com>"
      mail__transport: SMTP
      mail__options__host: mail.example.com
      mail__options__port: 587
      mail__options__secureConnection: "true"
      mail__options__auth__user: blog@example.com
      mail__options__auth__pass: actualPassword
    volumes:
      - /path/on/host/to/ghost_content:/var/lib/ghost/content
    hostname: blog
    networks:
      - nginx
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 750M

networks:
  nginx:
    external: true
