version: '3.7'
services:
  blog:
    image: ghost:2-alpine
    ports:
      - 2368:2368
    environment:
      url: https://blog.neigor.me
      mail__from: "'Ghost Blog' <blog@hashdivision.com>"
      mail__transport: SMTP
      mail__options__host: 172.17.0.1
      mail__options__port: 7664
    volumes:
      - ../content:/var/lib/ghost/content
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
      rollback_config:
        parallelism: 2
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 750M
